version: "2"

services:
  app:
    build:
      context: "."
    image: $DOCKER_IMAGE
    depends_on:
      - postgres
    environment:
      - CI
      - CODECLIMATE_REPO_TOKEN=efff74f42f6e9dff9daa21e21e8d8d2d3cb33f37b84a9d06bb907edb48a2cf6f
      - DOCKER=true
      - REBUILD_CACHE
    volumes:
      - .:/app
      - $BUILD_CACHE/bundler:/app/vendor/bundle

  rubocop:
    image: lendinghome/rubocop
    environment:
      - RUBOCOP_VERSION=2.3
    volumes:
      - .:/app
